before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
  format: tgz
  files:
  - info:
      mtime: "{{ .CommitDate }}"
  - src: CHANGELOG*
    dst: docs
  - src: LICENSE*
    dst: docs
  - src: README*
    dst: docs
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
release:
  github:
    owner: asphaltbuffet
    name: wherehouse
  prerelease: auto
announce:
  skip: "true"
dockers:
  -
    image_templates:
    - "docker.pkg.github.com/asphaltbuffet/wherehouse/{{ .ProjectName }}:latest"
    - "docker.pkg.github.com/asphaltbuffet/wherehouse/{{ .ProjectName }}:{{ .Major }}"
    - "docker.pkg.github.com/asphaltbuffet/wherehouse/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/asphaltbuffet/wherehouse/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
