version: '3'

includes:
  clean: ./taskfiles/Taskfile_{{OS}}.yml

tasks:
  default:
    cmds:
      - task: dev
  
  dev:
    desc: dev build
    deps: [ clean, install]
    cmds:
      - task: generate
      - task: vet
      - task: fmt
      - task: lint
      - task: test
      - task: mod-tidy
  
  ci:
    desc: CI build
    cmds:
      - task: dev
      - task: diff
  
  clean:
    desc: remove files created during build pipeline
    cmds:
      - task: clean:clean
  
  install:
    desc: go install tools
    cmds: 
      - cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1 
      - cmd: go install github.com/vektra/mockery/v2@latest
      - cmd: go get github.com/stretchr/testify/mock@v1.7.0

  install-build:
    desc: goreleaser install
    cmds:
      - cmd: go install github.com/goreleaser/goreleaser@v0.183.0

  
  generate:
    desc: go generate
    cmds:
      - go generate ./...
  
  vet:
    desc: go vet
    cmds:
      - go vet ./...
  
  fmt:
    desc: go fmt
    cmds:
      - go fmt ./...
  
  lint:
    desc: golangci-lint
    cmds:
      - golangci-lint run
  
  test:
    desc: go test with race detector and code coverage
    cmds:
      - go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
  
  mod-tidy:
    desc: go mod tidy
    cmds:
      - go mod tidy -compat=1.18
  
  diff:
    desc: git diff
    cmds:
      - git diff --exit-code
      - sh: RES=$$(git status --porcelain) ; if [ -n "$$RES" ]; then echo $$RES && exit 1 ; fi
  
  snapshot:
    desc: goreleaser --snapshot --skip-publish --rm-dist
    deps: [install, install-build]
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist
  
  release:
    desc: goreleaser --rm-dist
    deps: [install, install-build]
    cmds:
      - goreleaser --rm-dist
  
  run:
    desc: go run
    cmds:
      - go run -race .
  
  go-clean:
    desc: go clean build, test and modules caches
    cmds:
      - go clean -r -i -cache -testcache -modcache

  build:
    desc: go build
    cmds:
      - go build
