name: build

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: arduino/setup-task
        # You may pin to the exact commit or the version.
        # uses: arduino/setup-task@ca745e18916de727f841ec824ac20a615f1cddea
        uses: arduino/setup-task@v1.0.1
        with:
          # Version to use. Example: 3.4.2
          version: 3.x
          # Token with permissions to do repo things
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build
        run: task ci
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.*

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}

  release-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: arduino/setup-task
        # You may pin to the exact commit or the version.
        # uses: arduino/setup-task@ca745e18916de727f841ec824ac20a615f1cddea
        uses: arduino/setup-task@v1.0.1
        with:
          # Version to use. Example: 3.4.2
          version: 3.x
          # Token with permissions to do repo things
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release test
        run: task build
