name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: arduino/setup-task
        # You may pin to the exact commit or the version.
        # uses: arduino/setup-task@ca745e18916de727f841ec824ac20a615f1cddea
        uses: arduino/setup-task@v1.0.1
        with:
          # Version to use. Example: 3.4.2
          version: 3.x
          # Token with permissions to do repo things
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Docker login"
        run: docker login docker.pkg.github.com -u docker -p ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: task release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
